[project]
name = "greeter"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["example"]

[tool.uv.sources]
example = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
